//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffPage.OfficeHoursServRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OfficeHoursServRef.OfficeHoursServiceSoap")]
    public interface OfficeHoursServiceSoap {
        
        // CODEGEN: Generating message contract since element name profName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddOfficeHours", ReplyAction="*")]
        StaffPage.OfficeHoursServRef.AddOfficeHoursResponse AddOfficeHours(StaffPage.OfficeHoursServRef.AddOfficeHoursRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddOfficeHours", ReplyAction="*")]
        System.Threading.Tasks.Task<StaffPage.OfficeHoursServRef.AddOfficeHoursResponse> AddOfficeHoursAsync(StaffPage.OfficeHoursServRef.AddOfficeHoursRequest request);
        
        // CODEGEN: Generating message contract since element name profName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOfficeHours", ReplyAction="*")]
        StaffPage.OfficeHoursServRef.GetOfficeHoursResponse GetOfficeHours(StaffPage.OfficeHoursServRef.GetOfficeHoursRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOfficeHours", ReplyAction="*")]
        System.Threading.Tasks.Task<StaffPage.OfficeHoursServRef.GetOfficeHoursResponse> GetOfficeHoursAsync(StaffPage.OfficeHoursServRef.GetOfficeHoursRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddOfficeHoursRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddOfficeHours", Namespace="http://tempuri.org/", Order=0)]
        public StaffPage.OfficeHoursServRef.AddOfficeHoursRequestBody Body;
        
        public AddOfficeHoursRequest() {
        }
        
        public AddOfficeHoursRequest(StaffPage.OfficeHoursServRef.AddOfficeHoursRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddOfficeHoursRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string profName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string profTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string profLocation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string taName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string taTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string taLocation;
        
        public AddOfficeHoursRequestBody() {
        }
        
        public AddOfficeHoursRequestBody(string profName, string profTime, string profLocation, string taName, string taTime, string taLocation) {
            this.profName = profName;
            this.profTime = profTime;
            this.profLocation = profLocation;
            this.taName = taName;
            this.taTime = taTime;
            this.taLocation = taLocation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddOfficeHoursResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddOfficeHoursResponse", Namespace="http://tempuri.org/", Order=0)]
        public StaffPage.OfficeHoursServRef.AddOfficeHoursResponseBody Body;
        
        public AddOfficeHoursResponse() {
        }
        
        public AddOfficeHoursResponse(StaffPage.OfficeHoursServRef.AddOfficeHoursResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddOfficeHoursResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddOfficeHoursResult;
        
        public AddOfficeHoursResponseBody() {
        }
        
        public AddOfficeHoursResponseBody(string AddOfficeHoursResult) {
            this.AddOfficeHoursResult = AddOfficeHoursResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOfficeHoursRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOfficeHours", Namespace="http://tempuri.org/", Order=0)]
        public StaffPage.OfficeHoursServRef.GetOfficeHoursRequestBody Body;
        
        public GetOfficeHoursRequest() {
        }
        
        public GetOfficeHoursRequest(StaffPage.OfficeHoursServRef.GetOfficeHoursRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOfficeHoursRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string profName;
        
        public GetOfficeHoursRequestBody() {
        }
        
        public GetOfficeHoursRequestBody(string profName) {
            this.profName = profName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOfficeHoursResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOfficeHoursResponse", Namespace="http://tempuri.org/", Order=0)]
        public StaffPage.OfficeHoursServRef.GetOfficeHoursResponseBody Body;
        
        public GetOfficeHoursResponse() {
        }
        
        public GetOfficeHoursResponse(StaffPage.OfficeHoursServRef.GetOfficeHoursResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOfficeHoursResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetOfficeHoursResult;
        
        public GetOfficeHoursResponseBody() {
        }
        
        public GetOfficeHoursResponseBody(string GetOfficeHoursResult) {
            this.GetOfficeHoursResult = GetOfficeHoursResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OfficeHoursServiceSoapChannel : StaffPage.OfficeHoursServRef.OfficeHoursServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OfficeHoursServiceSoapClient : System.ServiceModel.ClientBase<StaffPage.OfficeHoursServRef.OfficeHoursServiceSoap>, StaffPage.OfficeHoursServRef.OfficeHoursServiceSoap {
        
        public OfficeHoursServiceSoapClient() {
        }
        
        public OfficeHoursServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OfficeHoursServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OfficeHoursServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OfficeHoursServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StaffPage.OfficeHoursServRef.AddOfficeHoursResponse StaffPage.OfficeHoursServRef.OfficeHoursServiceSoap.AddOfficeHours(StaffPage.OfficeHoursServRef.AddOfficeHoursRequest request) {
            return base.Channel.AddOfficeHours(request);
        }
        
        public string AddOfficeHours(string profName, string profTime, string profLocation, string taName, string taTime, string taLocation) {
            StaffPage.OfficeHoursServRef.AddOfficeHoursRequest inValue = new StaffPage.OfficeHoursServRef.AddOfficeHoursRequest();
            inValue.Body = new StaffPage.OfficeHoursServRef.AddOfficeHoursRequestBody();
            inValue.Body.profName = profName;
            inValue.Body.profTime = profTime;
            inValue.Body.profLocation = profLocation;
            inValue.Body.taName = taName;
            inValue.Body.taTime = taTime;
            inValue.Body.taLocation = taLocation;
            StaffPage.OfficeHoursServRef.AddOfficeHoursResponse retVal = ((StaffPage.OfficeHoursServRef.OfficeHoursServiceSoap)(this)).AddOfficeHours(inValue);
            return retVal.Body.AddOfficeHoursResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StaffPage.OfficeHoursServRef.AddOfficeHoursResponse> StaffPage.OfficeHoursServRef.OfficeHoursServiceSoap.AddOfficeHoursAsync(StaffPage.OfficeHoursServRef.AddOfficeHoursRequest request) {
            return base.Channel.AddOfficeHoursAsync(request);
        }
        
        public System.Threading.Tasks.Task<StaffPage.OfficeHoursServRef.AddOfficeHoursResponse> AddOfficeHoursAsync(string profName, string profTime, string profLocation, string taName, string taTime, string taLocation) {
            StaffPage.OfficeHoursServRef.AddOfficeHoursRequest inValue = new StaffPage.OfficeHoursServRef.AddOfficeHoursRequest();
            inValue.Body = new StaffPage.OfficeHoursServRef.AddOfficeHoursRequestBody();
            inValue.Body.profName = profName;
            inValue.Body.profTime = profTime;
            inValue.Body.profLocation = profLocation;
            inValue.Body.taName = taName;
            inValue.Body.taTime = taTime;
            inValue.Body.taLocation = taLocation;
            return ((StaffPage.OfficeHoursServRef.OfficeHoursServiceSoap)(this)).AddOfficeHoursAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StaffPage.OfficeHoursServRef.GetOfficeHoursResponse StaffPage.OfficeHoursServRef.OfficeHoursServiceSoap.GetOfficeHours(StaffPage.OfficeHoursServRef.GetOfficeHoursRequest request) {
            return base.Channel.GetOfficeHours(request);
        }
        
        public string GetOfficeHours(string profName) {
            StaffPage.OfficeHoursServRef.GetOfficeHoursRequest inValue = new StaffPage.OfficeHoursServRef.GetOfficeHoursRequest();
            inValue.Body = new StaffPage.OfficeHoursServRef.GetOfficeHoursRequestBody();
            inValue.Body.profName = profName;
            StaffPage.OfficeHoursServRef.GetOfficeHoursResponse retVal = ((StaffPage.OfficeHoursServRef.OfficeHoursServiceSoap)(this)).GetOfficeHours(inValue);
            return retVal.Body.GetOfficeHoursResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StaffPage.OfficeHoursServRef.GetOfficeHoursResponse> StaffPage.OfficeHoursServRef.OfficeHoursServiceSoap.GetOfficeHoursAsync(StaffPage.OfficeHoursServRef.GetOfficeHoursRequest request) {
            return base.Channel.GetOfficeHoursAsync(request);
        }
        
        public System.Threading.Tasks.Task<StaffPage.OfficeHoursServRef.GetOfficeHoursResponse> GetOfficeHoursAsync(string profName) {
            StaffPage.OfficeHoursServRef.GetOfficeHoursRequest inValue = new StaffPage.OfficeHoursServRef.GetOfficeHoursRequest();
            inValue.Body = new StaffPage.OfficeHoursServRef.GetOfficeHoursRequestBody();
            inValue.Body.profName = profName;
            return ((StaffPage.OfficeHoursServRef.OfficeHoursServiceSoap)(this)).GetOfficeHoursAsync(inValue);
        }
    }
}
