//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeHours.RatingReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RatingReference.RatingServiceSoap")]
    public interface RatingServiceSoap {
        
        // CODEGEN: Generating message contract since element name className from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRating", ReplyAction="*")]
        OfficeHours.RatingReference.GetRatingResponse GetRating(OfficeHours.RatingReference.GetRatingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRating", ReplyAction="*")]
        System.Threading.Tasks.Task<OfficeHours.RatingReference.GetRatingResponse> GetRatingAsync(OfficeHours.RatingReference.GetRatingRequest request);
        
        // CODEGEN: Generating message contract since element name className from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddRating", ReplyAction="*")]
        OfficeHours.RatingReference.AddRatingResponse AddRating(OfficeHours.RatingReference.AddRatingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddRating", ReplyAction="*")]
        System.Threading.Tasks.Task<OfficeHours.RatingReference.AddRatingResponse> AddRatingAsync(OfficeHours.RatingReference.AddRatingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRatingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRating", Namespace="http://tempuri.org/", Order=0)]
        public OfficeHours.RatingReference.GetRatingRequestBody Body;
        
        public GetRatingRequest() {
        }
        
        public GetRatingRequest(OfficeHours.RatingReference.GetRatingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRatingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string className;
        
        public GetRatingRequestBody() {
        }
        
        public GetRatingRequestBody(string className) {
            this.className = className;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRatingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRatingResponse", Namespace="http://tempuri.org/", Order=0)]
        public OfficeHours.RatingReference.GetRatingResponseBody Body;
        
        public GetRatingResponse() {
        }
        
        public GetRatingResponse(OfficeHours.RatingReference.GetRatingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRatingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetRatingResult;
        
        public GetRatingResponseBody() {
        }
        
        public GetRatingResponseBody(string GetRatingResult) {
            this.GetRatingResult = GetRatingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRatingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRating", Namespace="http://tempuri.org/", Order=0)]
        public OfficeHours.RatingReference.AddRatingRequestBody Body;
        
        public AddRatingRequest() {
        }
        
        public AddRatingRequest(OfficeHours.RatingReference.AddRatingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRatingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double rating;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string className;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool hasRatings;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool diffRating;
        
        public AddRatingRequestBody() {
        }
        
        public AddRatingRequestBody(double rating, string className, bool hasRatings, bool diffRating) {
            this.rating = rating;
            this.className = className;
            this.hasRatings = hasRatings;
            this.diffRating = diffRating;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRatingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRatingResponse", Namespace="http://tempuri.org/", Order=0)]
        public OfficeHours.RatingReference.AddRatingResponseBody Body;
        
        public AddRatingResponse() {
        }
        
        public AddRatingResponse(OfficeHours.RatingReference.AddRatingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddRatingResponseBody {
        
        public AddRatingResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RatingServiceSoapChannel : OfficeHours.RatingReference.RatingServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RatingServiceSoapClient : System.ServiceModel.ClientBase<OfficeHours.RatingReference.RatingServiceSoap>, OfficeHours.RatingReference.RatingServiceSoap {
        
        public RatingServiceSoapClient() {
        }
        
        public RatingServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RatingServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RatingServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RatingServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OfficeHours.RatingReference.GetRatingResponse OfficeHours.RatingReference.RatingServiceSoap.GetRating(OfficeHours.RatingReference.GetRatingRequest request) {
            return base.Channel.GetRating(request);
        }
        
        public string GetRating(string className) {
            OfficeHours.RatingReference.GetRatingRequest inValue = new OfficeHours.RatingReference.GetRatingRequest();
            inValue.Body = new OfficeHours.RatingReference.GetRatingRequestBody();
            inValue.Body.className = className;
            OfficeHours.RatingReference.GetRatingResponse retVal = ((OfficeHours.RatingReference.RatingServiceSoap)(this)).GetRating(inValue);
            return retVal.Body.GetRatingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OfficeHours.RatingReference.GetRatingResponse> OfficeHours.RatingReference.RatingServiceSoap.GetRatingAsync(OfficeHours.RatingReference.GetRatingRequest request) {
            return base.Channel.GetRatingAsync(request);
        }
        
        public System.Threading.Tasks.Task<OfficeHours.RatingReference.GetRatingResponse> GetRatingAsync(string className) {
            OfficeHours.RatingReference.GetRatingRequest inValue = new OfficeHours.RatingReference.GetRatingRequest();
            inValue.Body = new OfficeHours.RatingReference.GetRatingRequestBody();
            inValue.Body.className = className;
            return ((OfficeHours.RatingReference.RatingServiceSoap)(this)).GetRatingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OfficeHours.RatingReference.AddRatingResponse OfficeHours.RatingReference.RatingServiceSoap.AddRating(OfficeHours.RatingReference.AddRatingRequest request) {
            return base.Channel.AddRating(request);
        }
        
        public void AddRating(double rating, string className, bool hasRatings, bool diffRating) {
            OfficeHours.RatingReference.AddRatingRequest inValue = new OfficeHours.RatingReference.AddRatingRequest();
            inValue.Body = new OfficeHours.RatingReference.AddRatingRequestBody();
            inValue.Body.rating = rating;
            inValue.Body.className = className;
            inValue.Body.hasRatings = hasRatings;
            inValue.Body.diffRating = diffRating;
            OfficeHours.RatingReference.AddRatingResponse retVal = ((OfficeHours.RatingReference.RatingServiceSoap)(this)).AddRating(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OfficeHours.RatingReference.AddRatingResponse> OfficeHours.RatingReference.RatingServiceSoap.AddRatingAsync(OfficeHours.RatingReference.AddRatingRequest request) {
            return base.Channel.AddRatingAsync(request);
        }
        
        public System.Threading.Tasks.Task<OfficeHours.RatingReference.AddRatingResponse> AddRatingAsync(double rating, string className, bool hasRatings, bool diffRating) {
            OfficeHours.RatingReference.AddRatingRequest inValue = new OfficeHours.RatingReference.AddRatingRequest();
            inValue.Body = new OfficeHours.RatingReference.AddRatingRequestBody();
            inValue.Body.rating = rating;
            inValue.Body.className = className;
            inValue.Body.hasRatings = hasRatings;
            inValue.Body.diffRating = diffRating;
            return ((OfficeHours.RatingReference.RatingServiceSoap)(this)).AddRatingAsync(inValue);
        }
    }
}
