//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeHours.CommentsReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommentData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CommentData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        private System.DateTime TimestampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ClassID {
            get {
                return this.ClassIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassIDField, value) != true)) {
                    this.ClassIDField = value;
                    this.RaisePropertyChanged("ClassID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CommentsReference.CommentsServiceSoap")]
    public interface CommentsServiceSoap {
        
        // CODEGEN: Generating message contract since element name classId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetComments", ReplyAction="*")]
        OfficeHours.CommentsReference.GetCommentsResponse GetComments(OfficeHours.CommentsReference.GetCommentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetComments", ReplyAction="*")]
        System.Threading.Tasks.Task<OfficeHours.CommentsReference.GetCommentsResponse> GetCommentsAsync(OfficeHours.CommentsReference.GetCommentsRequest request);
        
        // CODEGEN: Generating message contract since element name classId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddComment", ReplyAction="*")]
        OfficeHours.CommentsReference.AddCommentResponse AddComment(OfficeHours.CommentsReference.AddCommentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddComment", ReplyAction="*")]
        System.Threading.Tasks.Task<OfficeHours.CommentsReference.AddCommentResponse> AddCommentAsync(OfficeHours.CommentsReference.AddCommentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCommentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetComments", Namespace="http://tempuri.org/", Order=0)]
        public OfficeHours.CommentsReference.GetCommentsRequestBody Body;
        
        public GetCommentsRequest() {
        }
        
        public GetCommentsRequest(OfficeHours.CommentsReference.GetCommentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCommentsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string classId;
        
        public GetCommentsRequestBody() {
        }
        
        public GetCommentsRequestBody(string classId) {
            this.classId = classId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCommentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCommentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public OfficeHours.CommentsReference.GetCommentsResponseBody Body;
        
        public GetCommentsResponse() {
        }
        
        public GetCommentsResponse(OfficeHours.CommentsReference.GetCommentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCommentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OfficeHours.CommentsReference.CommentData[] GetCommentsResult;
        
        public GetCommentsResponseBody() {
        }
        
        public GetCommentsResponseBody(OfficeHours.CommentsReference.CommentData[] GetCommentsResult) {
            this.GetCommentsResult = GetCommentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCommentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddComment", Namespace="http://tempuri.org/", Order=0)]
        public OfficeHours.CommentsReference.AddCommentRequestBody Body;
        
        public AddCommentRequest() {
        }
        
        public AddCommentRequest(OfficeHours.CommentsReference.AddCommentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCommentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string classId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string content;
        
        public AddCommentRequestBody() {
        }
        
        public AddCommentRequestBody(string classId, string username, string content) {
            this.classId = classId;
            this.username = username;
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCommentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCommentResponse", Namespace="http://tempuri.org/", Order=0)]
        public OfficeHours.CommentsReference.AddCommentResponseBody Body;
        
        public AddCommentResponse() {
        }
        
        public AddCommentResponse(OfficeHours.CommentsReference.AddCommentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCommentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddCommentResult;
        
        public AddCommentResponseBody() {
        }
        
        public AddCommentResponseBody(bool AddCommentResult) {
            this.AddCommentResult = AddCommentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CommentsServiceSoapChannel : OfficeHours.CommentsReference.CommentsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommentsServiceSoapClient : System.ServiceModel.ClientBase<OfficeHours.CommentsReference.CommentsServiceSoap>, OfficeHours.CommentsReference.CommentsServiceSoap {
        
        public CommentsServiceSoapClient() {
        }
        
        public CommentsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommentsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommentsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommentsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OfficeHours.CommentsReference.GetCommentsResponse OfficeHours.CommentsReference.CommentsServiceSoap.GetComments(OfficeHours.CommentsReference.GetCommentsRequest request) {
            return base.Channel.GetComments(request);
        }
        
        public OfficeHours.CommentsReference.CommentData[] GetComments(string classId) {
            OfficeHours.CommentsReference.GetCommentsRequest inValue = new OfficeHours.CommentsReference.GetCommentsRequest();
            inValue.Body = new OfficeHours.CommentsReference.GetCommentsRequestBody();
            inValue.Body.classId = classId;
            OfficeHours.CommentsReference.GetCommentsResponse retVal = ((OfficeHours.CommentsReference.CommentsServiceSoap)(this)).GetComments(inValue);
            return retVal.Body.GetCommentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OfficeHours.CommentsReference.GetCommentsResponse> OfficeHours.CommentsReference.CommentsServiceSoap.GetCommentsAsync(OfficeHours.CommentsReference.GetCommentsRequest request) {
            return base.Channel.GetCommentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<OfficeHours.CommentsReference.GetCommentsResponse> GetCommentsAsync(string classId) {
            OfficeHours.CommentsReference.GetCommentsRequest inValue = new OfficeHours.CommentsReference.GetCommentsRequest();
            inValue.Body = new OfficeHours.CommentsReference.GetCommentsRequestBody();
            inValue.Body.classId = classId;
            return ((OfficeHours.CommentsReference.CommentsServiceSoap)(this)).GetCommentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OfficeHours.CommentsReference.AddCommentResponse OfficeHours.CommentsReference.CommentsServiceSoap.AddComment(OfficeHours.CommentsReference.AddCommentRequest request) {
            return base.Channel.AddComment(request);
        }
        
        public bool AddComment(string classId, string username, string content) {
            OfficeHours.CommentsReference.AddCommentRequest inValue = new OfficeHours.CommentsReference.AddCommentRequest();
            inValue.Body = new OfficeHours.CommentsReference.AddCommentRequestBody();
            inValue.Body.classId = classId;
            inValue.Body.username = username;
            inValue.Body.content = content;
            OfficeHours.CommentsReference.AddCommentResponse retVal = ((OfficeHours.CommentsReference.CommentsServiceSoap)(this)).AddComment(inValue);
            return retVal.Body.AddCommentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OfficeHours.CommentsReference.AddCommentResponse> OfficeHours.CommentsReference.CommentsServiceSoap.AddCommentAsync(OfficeHours.CommentsReference.AddCommentRequest request) {
            return base.Channel.AddCommentAsync(request);
        }
        
        public System.Threading.Tasks.Task<OfficeHours.CommentsReference.AddCommentResponse> AddCommentAsync(string classId, string username, string content) {
            OfficeHours.CommentsReference.AddCommentRequest inValue = new OfficeHours.CommentsReference.AddCommentRequest();
            inValue.Body = new OfficeHours.CommentsReference.AddCommentRequestBody();
            inValue.Body.classId = classId;
            inValue.Body.username = username;
            inValue.Body.content = content;
            return ((OfficeHours.CommentsReference.CommentsServiceSoap)(this)).AddCommentAsync(inValue);
        }
    }
}
