//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberPage.HoursReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HoursReference.OfficeHoursServiceSoap")]
    public interface OfficeHoursServiceSoap {
        
        // CODEGEN: Generating message contract since element name profName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddOfficeHours", ReplyAction="*")]
        MemberPage.HoursReference.AddOfficeHoursResponse AddOfficeHours(MemberPage.HoursReference.AddOfficeHoursRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddOfficeHours", ReplyAction="*")]
        System.Threading.Tasks.Task<MemberPage.HoursReference.AddOfficeHoursResponse> AddOfficeHoursAsync(MemberPage.HoursReference.AddOfficeHoursRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddOfficeHoursRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddOfficeHours", Namespace="http://tempuri.org/", Order=0)]
        public MemberPage.HoursReference.AddOfficeHoursRequestBody Body;
        
        public AddOfficeHoursRequest() {
        }
        
        public AddOfficeHoursRequest(MemberPage.HoursReference.AddOfficeHoursRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddOfficeHoursRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string profName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string profTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string profLocation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string taName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string taTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string taLocation;
        
        public AddOfficeHoursRequestBody() {
        }
        
        public AddOfficeHoursRequestBody(string profName, string profTime, string profLocation, string taName, string taTime, string taLocation) {
            this.profName = profName;
            this.profTime = profTime;
            this.profLocation = profLocation;
            this.taName = taName;
            this.taTime = taTime;
            this.taLocation = taLocation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddOfficeHoursResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddOfficeHoursResponse", Namespace="http://tempuri.org/", Order=0)]
        public MemberPage.HoursReference.AddOfficeHoursResponseBody Body;
        
        public AddOfficeHoursResponse() {
        }
        
        public AddOfficeHoursResponse(MemberPage.HoursReference.AddOfficeHoursResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddOfficeHoursResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddOfficeHoursResult;
        
        public AddOfficeHoursResponseBody() {
        }
        
        public AddOfficeHoursResponseBody(string AddOfficeHoursResult) {
            this.AddOfficeHoursResult = AddOfficeHoursResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OfficeHoursServiceSoapChannel : MemberPage.HoursReference.OfficeHoursServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OfficeHoursServiceSoapClient : System.ServiceModel.ClientBase<MemberPage.HoursReference.OfficeHoursServiceSoap>, MemberPage.HoursReference.OfficeHoursServiceSoap {
        
        public OfficeHoursServiceSoapClient() {
        }
        
        public OfficeHoursServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OfficeHoursServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OfficeHoursServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OfficeHoursServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MemberPage.HoursReference.AddOfficeHoursResponse MemberPage.HoursReference.OfficeHoursServiceSoap.AddOfficeHours(MemberPage.HoursReference.AddOfficeHoursRequest request) {
            return base.Channel.AddOfficeHours(request);
        }
        
        public string AddOfficeHours(string profName, string profTime, string profLocation, string taName, string taTime, string taLocation) {
            MemberPage.HoursReference.AddOfficeHoursRequest inValue = new MemberPage.HoursReference.AddOfficeHoursRequest();
            inValue.Body = new MemberPage.HoursReference.AddOfficeHoursRequestBody();
            inValue.Body.profName = profName;
            inValue.Body.profTime = profTime;
            inValue.Body.profLocation = profLocation;
            inValue.Body.taName = taName;
            inValue.Body.taTime = taTime;
            inValue.Body.taLocation = taLocation;
            MemberPage.HoursReference.AddOfficeHoursResponse retVal = ((MemberPage.HoursReference.OfficeHoursServiceSoap)(this)).AddOfficeHours(inValue);
            return retVal.Body.AddOfficeHoursResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MemberPage.HoursReference.AddOfficeHoursResponse> MemberPage.HoursReference.OfficeHoursServiceSoap.AddOfficeHoursAsync(MemberPage.HoursReference.AddOfficeHoursRequest request) {
            return base.Channel.AddOfficeHoursAsync(request);
        }
        
        public System.Threading.Tasks.Task<MemberPage.HoursReference.AddOfficeHoursResponse> AddOfficeHoursAsync(string profName, string profTime, string profLocation, string taName, string taTime, string taLocation) {
            MemberPage.HoursReference.AddOfficeHoursRequest inValue = new MemberPage.HoursReference.AddOfficeHoursRequest();
            inValue.Body = new MemberPage.HoursReference.AddOfficeHoursRequestBody();
            inValue.Body.profName = profName;
            inValue.Body.profTime = profTime;
            inValue.Body.profLocation = profLocation;
            inValue.Body.taName = taName;
            inValue.Body.taTime = taTime;
            inValue.Body.taLocation = taLocation;
            return ((MemberPage.HoursReference.OfficeHoursServiceSoap)(this)).AddOfficeHoursAsync(inValue);
        }
    }
}
