//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeHours.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.OfficeHoursServiceSoap")]
    public interface OfficeHoursServiceSoap {
        
        // CODEGEN: Generating message contract since element name profName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddOfficeHours", ReplyAction="*")]
        OfficeHours.ServiceReference1.AddOfficeHoursResponse AddOfficeHours(OfficeHours.ServiceReference1.AddOfficeHoursRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddOfficeHours", ReplyAction="*")]
        System.Threading.Tasks.Task<OfficeHours.ServiceReference1.AddOfficeHoursResponse> AddOfficeHoursAsync(OfficeHours.ServiceReference1.AddOfficeHoursRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddOfficeHoursRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddOfficeHours", Namespace="http://tempuri.org/", Order=0)]
        public OfficeHours.ServiceReference1.AddOfficeHoursRequestBody Body;
        
        public AddOfficeHoursRequest() {
        }
        
        public AddOfficeHoursRequest(OfficeHours.ServiceReference1.AddOfficeHoursRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddOfficeHoursRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string profName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string profTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string profLocation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string taName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string taTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string taLocation;
        
        public AddOfficeHoursRequestBody() {
        }
        
        public AddOfficeHoursRequestBody(string profName, string profTime, string profLocation, string taName, string taTime, string taLocation) {
            this.profName = profName;
            this.profTime = profTime;
            this.profLocation = profLocation;
            this.taName = taName;
            this.taTime = taTime;
            this.taLocation = taLocation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddOfficeHoursResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddOfficeHoursResponse", Namespace="http://tempuri.org/", Order=0)]
        public OfficeHours.ServiceReference1.AddOfficeHoursResponseBody Body;
        
        public AddOfficeHoursResponse() {
        }
        
        public AddOfficeHoursResponse(OfficeHours.ServiceReference1.AddOfficeHoursResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddOfficeHoursResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddOfficeHoursResult;
        
        public AddOfficeHoursResponseBody() {
        }
        
        public AddOfficeHoursResponseBody(string AddOfficeHoursResult) {
            this.AddOfficeHoursResult = AddOfficeHoursResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OfficeHoursServiceSoapChannel : OfficeHours.ServiceReference1.OfficeHoursServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OfficeHoursServiceSoapClient : System.ServiceModel.ClientBase<OfficeHours.ServiceReference1.OfficeHoursServiceSoap>, OfficeHours.ServiceReference1.OfficeHoursServiceSoap {
        
        public OfficeHoursServiceSoapClient() {
        }
        
        public OfficeHoursServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OfficeHoursServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OfficeHoursServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OfficeHoursServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OfficeHours.ServiceReference1.AddOfficeHoursResponse OfficeHours.ServiceReference1.OfficeHoursServiceSoap.AddOfficeHours(OfficeHours.ServiceReference1.AddOfficeHoursRequest request) {
            return base.Channel.AddOfficeHours(request);
        }
        
        public string AddOfficeHours(string profName, string profTime, string profLocation, string taName, string taTime, string taLocation) {
            OfficeHours.ServiceReference1.AddOfficeHoursRequest inValue = new OfficeHours.ServiceReference1.AddOfficeHoursRequest();
            inValue.Body = new OfficeHours.ServiceReference1.AddOfficeHoursRequestBody();
            inValue.Body.profName = profName;
            inValue.Body.profTime = profTime;
            inValue.Body.profLocation = profLocation;
            inValue.Body.taName = taName;
            inValue.Body.taTime = taTime;
            inValue.Body.taLocation = taLocation;
            OfficeHours.ServiceReference1.AddOfficeHoursResponse retVal = ((OfficeHours.ServiceReference1.OfficeHoursServiceSoap)(this)).AddOfficeHours(inValue);
            return retVal.Body.AddOfficeHoursResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OfficeHours.ServiceReference1.AddOfficeHoursResponse> OfficeHours.ServiceReference1.OfficeHoursServiceSoap.AddOfficeHoursAsync(OfficeHours.ServiceReference1.AddOfficeHoursRequest request) {
            return base.Channel.AddOfficeHoursAsync(request);
        }
        
        public System.Threading.Tasks.Task<OfficeHours.ServiceReference1.AddOfficeHoursResponse> AddOfficeHoursAsync(string profName, string profTime, string profLocation, string taName, string taTime, string taLocation) {
            OfficeHours.ServiceReference1.AddOfficeHoursRequest inValue = new OfficeHours.ServiceReference1.AddOfficeHoursRequest();
            inValue.Body = new OfficeHours.ServiceReference1.AddOfficeHoursRequestBody();
            inValue.Body.profName = profName;
            inValue.Body.profTime = profTime;
            inValue.Body.profLocation = profLocation;
            inValue.Body.taName = taName;
            inValue.Body.taTime = taTime;
            inValue.Body.taLocation = taLocation;
            return ((OfficeHours.ServiceReference1.OfficeHoursServiceSoap)(this)).AddOfficeHoursAsync(inValue);
        }
    }
}
